# Name of the workflow
name: Create Flutter Release

# This workflow triggers when a new tag is pushed that starts with 'v' (e.g., v1.0.0, v1.2.3)
on:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs
jobs:
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # ✅ FIX: Set the default working directory for all run commands
    # Based on your screenshot, the Flutter project is in the 'gbbbs' subdirectory.
    defaults:
      run:
        working-directory: gbbbs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java environment required for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up the Flutter SDK environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 4: Install your project's dependencies
      # This will now correctly run inside the 'gbbbs' folder
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Update the app version in pubspec.yaml from the Git tag
      - name: Update Version
        run: |
          # Extract the version number from the tag (e.g., v1.0.1 -> 1.0.1)
          VERSION_NAME=${{ github.ref_name }}
          VERSION_NAME=${VERSION_NAME#v}
          
          # Use the GitHub run number as the build number for uniqueness
          BUILD_NUMBER=${{ github.run_number }}

          # Update the version line in the pubspec.yaml file
          sed -i "s/^version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml
          
          echo "Updated pubspec.yaml to version: $(grep '^version:' pubspec.yaml)"

      # Step 6: Build the release APK
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Create a formal GitHub Release and upload the APK as an asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # The name of the release will be the same as the tag
          name: Release ${{ github.ref_name }}
          # The body of the release can be automatically generated from your commits
          generate_release_notes: true
          # The path to the APK is now relative to the working-directory
          files: build/app/outputs/flutter-apk/app-release.apk